argo-cd:
  installCRDs: false      # As using helm3 set to "false" - Helm3 uses CRDs (previous config crd-install) in directories and will be installed before rendering the chart
  global:
    image:
      tag: v2.1.0         # ArgoCD Release version
  dex:
    enabled: false        # Disabled as we are not integrating with external providers
  server:
    extraArgs:
      - --insecure        # Using HTTP, hence why this flag
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm